export const USER_AUTH_CHECK_REQUEST = 'USER_AUTH_CHECK_REQUEST'
export const USER_AUTH_CHECK_SUCCESS = 'USER_AUTH_CHECK_SUCCESS'
export const USER_AUTH_CHECK_FAILURE = 'USER_AUTH_CHECK_FAILURE'

export const CART_ITEM_ADDED = 'CART_ITEM_ADDED'
export const CART_ITEM_REMOVED = 'CART_ITEM_REMOVED'
