const USER_AUTH_REQUEST = 'USER_AUTH_REQUEST'
const USER_AUTH_SUCCESS = 'USER_AUTH_SUCCESS'
const USER_AUTH_FAILURE = 'USER_AUTH_FAILURE'

const CART_ITEM_ADDED = 'CART_ITEM_ADDED'
const CART_ITEM_REMOVED = 'CART_ITEM_REMOVED'
