// Mutations.
export const ADD_ADDRESS = 'CAN_ADD_ADDRESS'
export const REMOVE_ADDRESS = 'CAN_REMOVE_ADDRESS'
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS'

export const ADD_ORDER = 'ADD_ORDER'
export const CANCEL_ORDER = 'CANCEL_ORDER'
export const REMOVE_PRODUCT_FROM_ORDER = 'REMOVE_PRODUCT_FROM_ORDER'
export const CHANGE_ORDER_STATUS = 'CHANGE_ORDER_STATUS'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'
export const UPDATE_PRODUCT_INFO = 'UPDATE_PRODUCT_INFO'
export const UPDATE_PRODUCT_IMAGES = 'UPDATE_PRODUCT_IMAGES'
export const UPDATE_PRODUCT_QUANTITY = 'UPDATE_PRODUCT_QUANTITY'

export const UPDATE_USER = 'UPDATE_USER'
export const CHANGE_USER_ROLE = 'CHANGE_USER_ROLE'

// Queries.
export const QUERY_ADDRESSES = 'QUERY_ADDRESSES'
export const QUERY_ADDRESS = 'QUERY_ADDRESS'

export const QUERY_ORDERS = 'QUERY_ORDERS'
export const QUERY_ORDER = 'QUERY_ORDER'

export const QUERY_PRODUCTS = 'QUERY_PRODUCTS'
export const QUERY_PRODUCT = 'QUERY_PRODUCT'

export const GET_ALL_USERS = 'GET_ALL_USERS'
export const GET_USER_BY_ID = 'GET_USER_BY_ID'
