// Mutations.
export const CAN_ADD_ADDRESS = 'CAN_ADD_ADDRESS'
export const CAN_REMOVE_ADDRESS = 'CAN_REMOVE_ADDRESS'
export const CAN_UPDATE_ADDRESS = 'CAN_UPDATE_ADDRESS'

export const CAN_ADD_ORDER = 'CAN_ADD_ORDER'
export const CAN_CANCEL_ORDER = 'CAN_CANCEL_ORDER'
export const CAN_REMOVE_PRODUCT_FROM_ORDER = 'CAN_REMOVE_PRODUCT_FROM_ORDER'
export const CAN_CHANGE_ORDER_STATUS = 'CAN_CHANGE_ORDER_STATUS'

export const CAN_ADD_PRODUCT = 'CAN_ADD_PRODUCT'
export const CAN_REMOVE_PRODUCT = 'CAN_REMOVE_PRODUCT'
export const CAN_UPDATE_PRODUCT_INFO = 'CAN_UPDATE_PRODUCT_INFO'
export const CAN_UPDATE_PRODUCT_IMAGES = 'CAN_UPDATE_PRODUCT_IMAGES'
export const CAN_UPDATE_PRODUCT_QUANTITY = 'CAN_UPDATE_PRODUCT_QUANTITY'

export const CAN_UPDATE_USER = 'CAN_UPDATE_USER'

// Queries.
export const CAN_QUERY_ADDRESSES = 'CAN_QUERY_ADDRESSES'
export const CAN_QUERY_ADDRESS = 'CAN_QUERY_ADDRESS'

export const CAN_QUERY_ORDERS = 'CAN_QUERY_ORDERS'
export const CAN_QUERY_ORDER = 'CAN_QUERY_ORDER'

export const CAN_QUERY_PRODUCTS = 'CAN_QUERY_PRODUCTS'
export const CAN_QUERY_PRODUCT = 'CAN_QUERY_PRODUCT'

export const CAN_GET_ALL_USERS = 'CAN_GET_ALL_USERS'
export const CAN_GET_USER_BY_ID = 'CAN_GET_USER_BY_ID'
